app/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.view, name="home"),
    path('wedki', views.Rods_view, name="wedki"),
    path('kolowrotki', views.Rells_view, name="kolowrotki"),
    path('product/<int:pk>/', views.ProductDetailView.as_view(), name='product-detail'),
    path('sign_up/', views.register, name='sign_up'),
    path('login/', views.loginView, name='login'),
    path('logout/', views.logout_view, name='logout'),

 ]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payment/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('profile/', views.UserProfileListView.as_view(), name='profile-list'),
    path('add-user-profile/', views.add_user_profile, name="add-user-profile"),
    path('user-profile/<int:pk>/', views.UserProfileDetailView.as_view(), name="user-profile"),
    path('profiles/<int:pk>/edit/', views.UserProfileUpdateView.as_view(), name='profile-edit'),
    path('profiles/<int:pk>/delete/', views.UserProfileDeleteView.as_view(), name='profile-delete'),
    path('order-summary/', views.order_summary, name='order-summary'),
    path('create-checkout-session/', views.create_checkout_session, name='create_checkout_session'),
    path('succes/', views.PaymentSucces.as_view(), name='payment-success'),
    path('cancel/', views.PaymentCancel.as_view(), name='payment-cancel'),
    path('webhook-stripe/', views.StripeWebhookView.as_view(), name='webhook-stripe'),
    path('order-history/', views.order_history, name='order-history'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sklep/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('cart/', include('cart.urls')),
    path('payment/', include('payment.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payment/models.py
from django.db import models
from django.contrib.auth.models import User
from app .models import Product

class UserProfile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    adress = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    country= models.CharField(max_length=100)

    def __str__(self):
        return f'ADRES: {self.adress} || USER: {self.user}'
    
class Order(models.Model):
    PAYMENT_STATUS_CHOICES = [
        ('pending', 'Oczekujące'),
        ('paid', 'Zapłacone'),
        ('failed', 'Nieudane'),
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    order_number = models.CharField(max_length=100, unique=True)
    total_amount = models.DecimalField(max_digits=10, decimal_places=2)
    payment_status = models.CharField(max_length=10, choices=PAYMENT_STATUS_CHOICES)
    stripe_payment_intent = models.CharField(max_length=255, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Zamówienie {self.order_number} przez {self.user.username}"
    
class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.PROTECT)
    quantity = models.PositiveIntegerField()
    price = models.DecimalField(max_digits=10, decimal_places=2)  # Cena jednostkowa

    def __str__(self):
        return f"{self.quantity} x {self.product.name} w zamówieniu {self.order.order_number}"

payment/forms.py
from django import forms
from .models import UserProfile

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['full_name', 'email', 'adress', 'city', 'country']
        widgets = {
            'full_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Full Name'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email'}),
            'adress': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Address'}),
            'city': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'City'}),
            'country': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Country'}),
        }

payment/views.py
from django.shortcuts import render, redirect
from .forms import UserProfileForm
from django.contrib import messages
from django.views.generic.edit import UpdateView, DeleteView, UpdateView
from django.views.generic.detail import DetailView
from .models import UserProfile, OrderItem
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from cart.cart import Cart
from .models import UserProfile, Order
from django.views.generic import TemplateView
from django.urls import reverse
import uuid
from django.http import JsonResponse
import logging
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View

@login_required
def add_user_profile(request):
    if request.method == 'POST':
        form = UserProfileForm(request.POST)
        if form.is_valid():
            user_profile = form.save(commit=False)
            user_profile.user = request.user  
            user_profile.save()
            messages.success(request, "Udało Ci się utworzyć profil użytkownika")  
            return redirect("profile-list")
    else:
        form = UserProfileForm()
    
    return render(request, 'add_user_profile.html', {'form': form})


class UserProfileListView(LoginRequiredMixin,ListView):
    model = UserProfile
    template_name = 'user_profile_list.html'
    context_object_name = 'profiles'

    def get_queryset(self):
        return UserProfile.objects.filter(user=self.request.user)

class UserProfileDetailView(LoginRequiredMixin,DetailView):
    model = UserProfile
    template_name = 'user_profile_detail.html'
    context_object_name = 'profile'

class UserProfileUpdateView(LoginRequiredMixin,UpdateView):
    model = UserProfile
    form_class = UserProfileForm
    template_name = 'user_profile_update.html'
    success_url = reverse_lazy('profile-list')

class UserProfileDeleteView(LoginRequiredMixin,DeleteView):
    model = UserProfile
    template_name = 'user_profile_delete.html'
    success_url = reverse_lazy('profile-list')

import stripe
from django.conf import settings
from django.shortcuts import render, redirect

@login_required
def order_summary(request):
    cart = Cart(request)
    cart_products = cart.get_prods
    quantities = cart.get_quants
    totals = cart.cart_total()
    try:
        userprofile = UserProfile.objects.get(user=request.user)
    except UserProfile.DoesNotExist:
        userprofile = None

    context = {
        "cart_products": cart_products,
        "quantities": quantities,
        "totals": totals,
        "userprofile" : userprofile,
    }

    return render(request, "order_summary.html", context)

@login_required
def create_checkout_session(request):
    order_number = str(uuid.uuid4())[:8]
    cart = Cart(request)
    cart_products = cart.get_prods
    quantities = cart.get_quants

    total_amount = cart.cart_total()

    # Tworzenie zamówienia
    order = Order.objects.create(
        user=request.user,
        order_number=order_number,
        total_amount=total_amount,
        payment_status='pending'
    )

    # Tworzenie pozycji zamówienia
    for product in cart_products:
        quantity = quantities[str(product.id)]
        OrderItem.objects.create(
            order=order,
            product=product,
            quantity=quantity,
            price=product.price
        )

    # Tworzenie line_item dla Stripe (jeden z łączną kwotą)
    product_names = ', '.join([f"{product.name} (x{quantities[str(product.id)]})" for product in cart_products])

    total_amount_grosze = int(total_amount * 100)

    line_items = [{
        'price_data': {
            'currency': 'pln',
            'product_data': {
                'name': product_names,
            },
            'unit_amount': total_amount_grosze,
        },
        'quantity': 1,
    }]

    # Tworzenie sesji Stripe Checkout
    stripe.api_key = settings.STRIPE_SECRET_KEY

    session = stripe.checkout.Session.create(
        payment_method_types=['card', 'blik'],
        line_items=line_items,
        mode='payment',
        success_url=request.build_absolute_uri(reverse('payment-success')),
        cancel_url=request.build_absolute_uri(reverse('payment-cancel')),
        metadata={
            'order_number': order_number,
            'user_id': request.user.id,
        }
    )

    return redirect(session.url, code=303)


class PaymentSucces(LoginRequiredMixin,TemplateView):
    template_name = "payment_succes.html"

class PaymentCancel(LoginRequiredMixin,TemplateView):
    template_name = "payment_cancel.html"

logger = logging.getLogger(__name__)

from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
stripe.api_key = settings.STRIPE_SECRET_KEY
endpoint_secret = settings.STRIPE_WEBHOOK_SECRET  

@method_decorator(csrf_exempt, name='dispatch')
class StripeWebhookView(View):
    def post(self, request, *args, **kwargs):
        payload = request.body
        sig_header = request.META.get('HTTP_STRIPE_SIGNATURE')
        event = None

        try:
            event = stripe.Webhook.construct_event(
                payload, sig_header, endpoint_secret
            )
        except ValueError as e:
            # Niepoprawny ładunek
            return JsonResponse({'status': 'invalid payload'}, status=400)
        except stripe.error.SignatureVerificationError as e:
            # Niepoprawna sygnatura
            return JsonResponse({'status': 'invalid signature'}, status=400)

        # Obsługa zdarzeń
        if event['type'] == 'payment_intent.succeeded':
            payment_intent = event['data']['object']
            handle_successful_payment(payment_intent)

        return JsonResponse({'status': 'success'})

def handle_successful_payment(payment_intent):
    try:
        # Znajdź zamówienie na podstawie identyfikatora PaymentIntent
        order = Order.objects.get(stripe_payment_intent=payment_intent['id'])
        order.payment_status = 'paid'  # Zaktualizuj status na 'zapłacone'
        order.save()
    except Order.DoesNotExist:
        # Obsłuż przypadek, gdy zamówienie nie istnieje
        pass

@login_required
def order_history(request):
    user = request.user
    orders = Order.objects.filter(user=user).order_by('-created_at')  # Zamówienia posortowane od najnowszych

    # Przekazujemy zamówienia do szablonu
    return render(request, 'order_history.html', {'orders': orders})

payment/templates/add_user_profile.html
<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dodaj profil użytkownika</title>
</head>
<body>
    {% include "docs/header.html" %}
    <div class="container">
        <h1>Dodaj profil użytkownika</h1>
        <form method="POST" action="">
            {% csrf_token %}
            {{ form.as_p }}  

            <button type="submit">Zapisz profil</button>
        </form>

        
    </div>
</body>
</html>

payment/templates/checkout.html
<form action="{% url 'create_checkout_session' %}" method="POST">
    {% csrf_token %}
    <button type="submit" id="checkout-button">Zapłać teraz</button>
  </form>
  
  <script src="https://js.stripe.com/v3/"></script>
  <script>
      var stripe = Stripe("{{ STRIPE_PUBLISHABLE_KEY }}");
  
      var checkoutButton = document.getElementById('checkout-button');
  
      checkoutButton.addEventListener('click', function() {
          fetch("{% url 'create_checkout_session' %}", {
              method: 'POST',
              headers: {
                  'X-CSRFToken': '{{ csrf_token }}',
              }
          })
          .then(function(response) {
              return response.json();
          })
          .then(function(session) {
              return stripe.redirectToCheckout({ sessionId: session.id });
          })
          .then(function(result) {
              if (result.error) {
                  alert(result.error.message);
              }
          })
          .catch(function(error) {
              console.error('Error:', error);
          });
      });
  </script>
  

payment/templates/order_history.html
{% load static %}
{% load custom_filters %}
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Podsumowanie zamówienia</title>
    <link rel="stylesheet" href="{% static 'css/order_summary.css' %}">
    
</head>
<body>
    {% include "docs/header.html" %}
    <h1>Historia Zamówień</h1>
    {% if orders %}
        {% for order in orders %}
            <h2>Zamówienie nr {{ order.order_number }} - {{ order.created_at }}</h2>
            <p><strong>Status płatności:</strong> {{ order.get_payment_status_display }}</p>
            <p><strong>Łączna kwota:</strong> {{ order.total_amount }} PLN</p>
            <table>
                <thead>
                    <tr>
                        <th>Produkt</th>
                        <th>Ilość</th>
                        <th>Cena jednostkowa</th>
                        <th>Łącznie</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in order.items.all %}
                        <tr>
                            <td>{{ item.product.name }}</td>
                            <td>{{ item.quantity }}</td>
                            <td>{{ item.price }} PLN</td>
                            <td>{{ item.quantity|multiply:item.price }} PLN</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% endfor %}
    {% else %}
        <p>Nie masz jeszcze żadnych zamówień.</p>
    {% endif %}
<script src={% static "js/bootstrap.bundle.min.js" %}></script>
</body>
</html>

payment/templates/order_summary.html
{% load static %}
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Podsumowanie zamówienia</title>
    <link rel="stylesheet" href="{% static 'css/order_summary.css' %}">
    
</head>
<body>
    {% include "docs/header.html" %}
    <main class="order-summary-page">
        <div class="container">
            <h1>Podsumowanie zamówienia</h1>

            <!-- Dane użytkownika -->
            <div class="user-info">
                <h2>Dane użytkownika</h2>
                {% if userprofile %}
                    <p><strong>Imię i nazwisko:</strong> {{ userprofile.full_name }}</p>
                    <p><strong>Email:</strong> {{ userprofile.email }}</p>
                    <p><strong>Adres:</strong> {{ userprofile.adress }}</p>
                    <p><strong>Miasto:</strong> {{ userprofile.city }}</p>
                    <p><strong>Kraj:</strong> {{ userprofile.country }}</p>
                {% else %}
                    <p>Nie znaleziono danych użytkownika. <a href="{% url 'add-user-profile' %}">Utwórz profil</a>.</p>
                {% endif %}
            </div>

            <!-- Podsumowanie koszyka -->
            <div class="order-summary">
                <h2>Twoje zamówienie</h2>
                <table class="cart-table">
                    <thead>
                        <tr>
                            <th>Produkt</th>
                            <th>Ilość</th>
                            <th>Cena</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for item in cart_products %}
                        <tr class="cart-item" data-product-id="{{ item.id }}">
                            <td>
                                <img src="{{ item.img.url }}" class="item-image" alt="{{ item.name }}">
                                {{ item.name }}
                            </td>
                            <td>
                                {% for key, value in quantities.items %}
                                    {% if key == item.id|stringformat:"s" %}
                                        {{ value }}
                                    {% endif %}
                                {% endfor %}
                            </td>
                            <td>
                                {% for key, value in quantities.items %}
                                    {% if key == item.id|stringformat:"s" %}
                                        {{ item.price}} zł
                                    {% endif %}
                                {% endfor %}
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            
            <!-- Podsumowanie cen -->
            <div class="total-summary">
                <h3>Podsumowanie kwoty</h3>
                <p><strong>Łącznie do zapłaty:</strong> {{ totals }} zł</p>
            </div>

            <!-- Formularz płatności -->
            <form id="payment-form" method="post" action="{% url 'create_checkout_session' %}">
                {% csrf_token %}
                
                <!-- Przyciski płatności bez potrzeby elementu karty -->
                {% if userprofile %}
                    <button class="payment-btn" type="submit">Zamawiam i płacę</button>
                {% else %}
                    <p>Uzupełnij swój <a href="{% url "add-user-profile" %}">profil</a>, abyśmy wiedzieli na jaki adres wysłać zamówienie</p>
                {% endif %}
            </form>
            </form>
        </div>
    </main>

    <script src={% static "js/bootstrap.bundle.min.js" %}></script>
    
</body>
</html>

payment/templates/payment_cancel.html
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Płatność Anulowana</title>
</head>
<body>
    <header>
        <h1>Płatność Anulowana</h1>
    </header>
    <main>
        <p>Twoja płatność została anulowana.</p>
        <p>Jeśli potrzebujesz pomocy, skontaktuj się z nami.</p>
        <a href="{% url 'cart_summary' %}">Powrót do koszyka</a>
    </main>
    <footer>
        <p>&copy; 2024 Twoja Firma</p>
    </footer>
</body>
</html>

payment/templates/payment_succes.html
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Płatność Zakończona Sukcesem</title>
</head>
<body>
    <header>
        <h1>Dziękujemy za zakupy!</h1>
    </header>
    <main>
        <p>Twoja płatność została przetworzona pomyślnie.</p>
        <p>Otrzymasz potwierdzenie na podany adres e-mail.</p>
        <a href="{% url 'home' %}">Wróć do strony głównej</a>
        <p><a href="{% url 'order-history' %}">Zobacz historię swojego zamówienia</a><p>
    </main>
    <footer>
        <p>&copy; Sklep Wędkarski </p>
    </footer>
</body>
</html>

payment/templates/user_profile_delete.html
{% load static %}
<head>
    <link rel="stylesheet" href="{% static "css/delete_profile.css" %}">
</head>

<body>
    <div class="delete-profile-container">
        <h1>Usunąć profil: {{ object.full_name }} ?</h1>
        <form method="post">
            {% csrf_token %}
            <p>Czy jesteś pewny, ze chcesz usunąć profil?</p>
            <button type="submit">Usuń</button>
            <a href="{% url 'profile-list' %}">Wróć</a>
        </form>
    </div>
    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
</body>

payment/templates/user_profile_detail.html
{% load static %}
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static "css/rods.css" %}">
        <link rel="stylesheet" href="{% static "css/quantity.css" %}">
    </head>
    <body>
        {% include "docs/header.html" %}
        <main>
            <ul class="container text-center">
                <li><h2>Imię i nazwisko:</h2>{{profile.full_name}}</li>
                <li><h2>Email:</h2> {{profile.email}} </li>
                <li>Ulica: {{profile.adress}} </li>
                <li>Miasto: {{profile.city}} </li>
                <li>Kraj: {{profile.country}} </li>
            </ul>
        </main>
        <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
    </body>

payment/templates/user_profile_list.html
<!DOCTYPE html>
<html lang="pl">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lista profili użytkowników</title>
    <link rel="stylesheet" href="{% static "css/user_profile_list.css" %}">
</head>
<body>
    {% include "docs/header.html" %}
        <div class="profile-section">
            <div class="container">
                <h1 class="container text-center">Dane użytkownika: {{request.user}}</h1>
        
                {% if profiles %}
                    <ul class="container text-center">
                        {% for profile in profiles %}
                            <li><span>{{ profile.full_name }}</span></li>
                            <li><span>{{ profile.email }}</span></li>
                            <li><span>{{ profile.adress }}</span></li>
                            <li><span>{{ profile.city }}</span></li>
                            <li><span>{{ profile.country }}</span></li>
                            <li><a href="{% url 'profile-edit' profile.pk %}" class="edit-btn">Edytuj</a>
                            <li><a href="{% url 'profile-delete' profile.pk %}" class="delete-btn">Usuń</a>
                        {% endfor %}
                    </ul>
                {% else %}
                    <p>Nie masz jeszcze żadnych profili. <a href="{% url 'add-user-profile' %}">Utwórz nowy profil</a>.</p>
                {% endif %}
            </div>
        </div>
    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
    <script src={% static "js/bootstrap.bundle.min.js" %}></script>
    
</body>
</html>

payment/templates/user_profile_update.html
<!DOCTYPE html>
{% load static %}
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edytuj profil użytkownika</title>
    <link rel="stylesheet" href="{% static 'css/update-profile.css' %}">
</head>
<body>
    <div class="update-profile-container">
        <h1>Edytuj profil użytkownika</h1>
        <form method="POST" action="">
            {% csrf_token %}
            {{ form.as_p }}
    
            <button type="submit">Zapisz zmiany</button>
        </form>
    </div>
    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
</body>
</html>